spring:
  profiles:
    active: dev
---
server:
  port: 3355
spring:
  application:
    name: spring-cloud-config-client
  profiles:dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/